pub const INPUTS: [&str; 13] = [
    include_str!("../inputs/day01.txt"),
    include_str!("../inputs/day02.txt"),
    include_str!("../inputs/day03.txt"),
    include_str!("../inputs/day04.txt"),
    include_str!("../inputs/day05.txt"),
    include_str!("../inputs/day06.txt"),
    include_str!("../inputs/day07.txt"),
    include_str!("../inputs/day08.txt"),
    include_str!("../inputs/day09.txt"),
    include_str!("../inputs/day10.txt"),
    include_str!("../inputs/day11.txt"),
    include_str!("../inputs/day12.txt"),
    include_str!("../inputs/day13.txt"),
];