[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "benchmark"
harness = false

[dependencies]
regex = "1"
itertools = "0.13"
queues = "1"

[dev-dependencies]
criterion = "0.5"