[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "benchmark"
harness = false

[dependencies]
regex = "1.10.2"
itertools = "0.12.0"

[dev-dependencies]
criterion = "0.5.1"